
language: java

sudo : false

jdk:
  - openjdk10

services:
  - docker

install:
  - mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 0ad6bddf-6aeb-4790-97dc-fc6ac8be6dd3
